[package]
name = "use-existing"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
toml = { workspace = true }
load_file = "1.0.1"

counter.workspace = true

lib = { path = "../crates/lib" }