[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "new_contract"

[[bin]]
name = "existing_contract"

[[bin]]
name = "keystore"

[dependencies]
alloy = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
load_file = "1.0.1"
rand = "0.8.5"
tempfile = "3.15.0"

counter.workspace = true

