[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "new_contract"
src = "src/new_contract.rs"

[[bin]]
name = "existing_contract"
src = "src/existing_contract.rs"

[[bin]]
name = "keystore"
src = "src/keystore.rs"

[dependencies]
alloy = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
toml = { workspace = true }
load_file = "1.0.1"
rand = "0.8.5"
tempfile = "3.15.0"

counter.workspace = true

